services:
  rabotDB:
      container_name: rabotDB
      restart: always
      image: mongo:latest
      ports:
          - 27017:27017

  app:
      container_name: rabot
      restart: always
      build:
        context: .
        dockerfile: Dockerfile.dev
      cap_add:
        - SYS_ADMIN
      command: yarn dev
      volumes:
          - .:/app
          - nodemodules:/app/node_modules
      links:
          - rabotDB
      depends_on: 
          - rabotDB
      env_file: .env

volumes:
  nodemodules: {}